from bank import *
from time import sleep


records = list()
print('CADASTRAR CONTA')
name = input('Nome: ')
surname = input('Sobrenome: ')
cpf = input('CPF: ')
client1 = Client(name, surname, cpf)
acc1 = Account(client1, 0)
records.append({'cliente 1':client1, 'conta 1':acc1})
acc1.deposit(300)
acc1.extract()
print()
client2 = Client('João', 'Querino', 4863)
acc2 = Account(client2, 0)
acc2.extract()
print()
acc1.transfer_to(acc2, 400)
acc1.extract()
print()
acc2.extract()
acc1.transfer_to(acc2, 150)
acc1.withdraw(50)
acc1.historic.printh()
print(acc1.create)
sleep(10)
print(acc1.create)
